// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/dashboard-clean-minimalist/CleanMinimalist.tsx": () => import("../components/mockups/dashboard-clean-minimalist/CleanMinimalist.tsx"),
  "./components/mockups/dashboard-dark-academic/DarkAcademic.tsx": () => import("../components/mockups/dashboard-dark-academic/DarkAcademic.tsx"),
  "./components/mockups/dashboard-vibrant/VibrantModern.tsx": () => import("../components/mockups/dashboard-vibrant/VibrantModern.tsx")
};
